### PR TITLE
Adding missing parameter for IKCONFIG bootup availability

### PR DESCRIPTION
**Pull request by Flohack74**

### CODE REVIEW

**Comment by Flohack74** [comment]
Please review and accept or decline.

**Comment by krnlyng** [comment]
hi @Flohack74, we already check for IKCONFIG_PROC which depends on IKCONFIG. can you elaborate why this is necessary?
i am not sure if we should include all dependencies of all CONFIG_s we require and cause bloat, but if there is a reason to have this particular one, we can do it :).

**Comment by Flohack74** [comment]
The reason is that the script complains about this parameter, you set it, and still cannot boot. That's because not everyone knows kernel parameters so well to immediately understand: well, I also must set the parent parameter correctly. Many people who never touched a kernel before are now trying to help porting, and it should be made as easy as possible. That means: Script checks for ALL parameters that Halium needs. And that does not bloat the script, it saves a lot of headache and frustration, and also support time in the chat like:
"I followed your documents, it does not work, your documents are bad" - "Did you set parameter xy?" - "No, its not documented" - "But you need to set it to make it work" - "why it's not in the script then?" - "..."

A script is a documentation, too, so we should be as explicit as possible.

**Comment by krnlyng** [comment]
the script will print an error as long as the config is not set. and this config will not be set until CONFIG_IKCONFIG is also enabled since it is a dependancy of it:
https://cateee.net/lkddb/web-lkddb/IKCONFIG_PROC.html

**Comment by Flohack74** [comment]
So you are telling me, the checker tells me to set x, then I try to compile, then kernel build system that I also need y? A small improvement over letting people install the thingie and not getting access, but still not what I want: I want a checker that checks everthing, since it saves time and, again I repeat myself, frustration of having to iterate over the build process many times. Porting is no fun already, lets make it as easy as possible. Ubuntu Touch has the automatic fixer that just rewrites the kernel config, and I am done.

**Comment by krnlyng** [comment]
@flohack74 what i am saying is that we use many different kernels and in some cases before building the kernel for at least one initial time we cannot know what configs will be added/removed when the kernel build system processes the defconfig.

**Pull request closed without merging**
